#!/usr/bin/env python3
"""Manage the translation-gap issue opened by the translation-audit workflow.

``open`` renders audit findings (``audit_translations.py --json``) as a
deterministic issue body and creates the issue, or edits the existing one only
when its content changed, so daily runs do not spam the timeline. ``close``
closes the issue once the audit passes.

All GitHub access goes through the ``gh`` CLI with GITHUB_TOKEN set; every
``gh`` call is injectable, which keeps the decision logic unit-testable.

    python translation_issue.py open findings.json
    python translation_issue.py close
"""

import json
import os
import subprocess
import sys

ISSUE_TITLE = "Translation audit: add-ons still publishing non-English text"
ISSUE_LABEL = "translation-gap"
ISSUE_LABEL_COLOR = "e99695"
LABEL_DESCRIPTION = "Add-ons the mirror still publishes without English metadata"


def default_gh(args):
    """Run one gh CLI command and return (returncode, stdout)."""
    completed = subprocess.run(
        ["gh", *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return completed.returncode, completed.stdout


def _fenced(text):
    """Wrap text in a code fence long enough to survive backticks inside it."""
    fence = "```"
    while fence in text:
        fence += "`"
    return f"{fence}\n{text}\n{fence}"


def render_body(findings, repository):
    """Render findings as the deterministic issue body."""
    count = len(findings)
    noun = "add-on" if count == 1 else "add-ons"
    lines = [
        f"The translation audit found {count} {noun} still publishing "
        "non-English text in the live mirror.",
        "",
        "To fix: add an English `summary` and `description` for each add-on "
        "ID below to `translations.json`, then let the next hourly build "
        "publish them. `audit_translations.py` documents the detection "
        "rules; borrow style from the existing entries.",
        "",
        f"{len(findings)} untranslated {noun}:",
        "",
    ]
    for finding in findings:
        source = finding.get("sourceURL") or "no source URL"
        lines.append(f"### `{finding['addonId']}` ({source})")
        lines.append("")
        for field, detail in finding["fields"].items():
            text = " ".join((detail["text"] or "").split())
            if len(text) > 600:
                text = text[:597] + "..."
            lines.append(f"- `{field}` [{detail['reason']}]:")
            lines.append("")
            lines.append("  " + _fenced(text).replace("\n", "\n  "))
        lines.append("")
    lines.append(
        "<sub>Generated by the "
        f"[translation-audit workflow](https://github.com/{repository}/"
        "actions/workflows/translation-audit.yml). This issue closes "
        "automatically once the audit passes.</sub>"
    )
    return "\n".join(lines)


def find_open_issue(gh=default_gh, repository=None):
    """Return the number of the open gap issue, or None when there is none."""
    repository = repository or os.environ["GITHUB_REPOSITORY"]
    code, out = gh(
        [
            "issue", "list",
            "--repo", repository,
            "--state", "open",
            "--search", ISSUE_TITLE,
            "--json", "number,title",
        ]
    )
    if code != 0:
        raise RuntimeError(f"gh issue list failed: {out}")
    for issue in json.loads(out or "[]"):
        if issue.get("title") == ISSUE_TITLE:
            return issue["number"]
    return None


def ensure_label(gh=default_gh, repository=None):
    """Create the gap label; an existing label makes the create fail, which is fine."""
    repository = repository or os.environ["GITHUB_REPOSITORY"]
    gh(
        [
            "label", "create", ISSUE_LABEL,
            "--repo", repository,
            "--description", LABEL_DESCRIPTION,
            "--color", ISSUE_LABEL_COLOR,
        ]
    )


def open_issue(findings_path, gh=default_gh, repository=None):
    """Create or update the gap issue from a findings JSON file."""
    repository = repository or os.environ["GITHUB_REPOSITORY"]
    with open(findings_path, "r", encoding="utf-8") as handle:
        findings = json.load(handle)
    body = render_body(findings, repository)
    number = find_open_issue(gh, repository)
    if number is None:
        ensure_label(gh, repository)
        code, out = gh(
            [
                "issue", "create",
                "--repo", repository,
                "--title", ISSUE_TITLE,
                "--body", body,
                "--label", ISSUE_LABEL,
            ]
        )
        if code != 0:
            raise RuntimeError(f"gh issue create failed: {out}")
        print(f"Opened the translation-gap issue: {out.strip()}")
        return
    code, out = gh(
        ["issue", "view", str(number), "--repo", repository, "--json", "body"]
    )
    if code == 0:
        current = json.loads(out or "{}").get("body", "")
        if current == body:
            print(f"Issue #{number} already matches the current findings.")
            return
    code, out = gh(
        ["issue", "edit", str(number), "--repo", repository, "--body", body]
    )
    if code != 0:
        raise RuntimeError(f"gh issue edit failed: {out}")
    print(f"Updated issue #{number} with the current findings.")


def close_issue(gh=default_gh, repository=None):
    """Close the gap issue when the audit no longer finds untranslated text."""
    repository = repository or os.environ["GITHUB_REPOSITORY"]
    number = find_open_issue(gh, repository)
    if number is None:
        print("No open translation-gap issue; nothing to close.")
        return
    code, out = gh(
        [
            "issue", "close", str(number),
            "--repo", repository,
            "--comment",
            "The daily translation audit no longer finds untranslated "
            "add-ons; closing automatically.",
        ]
    )
    if code != 0:
        raise RuntimeError(f"gh issue close failed: {out}")
    print(f"Closed issue #{number}.")


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if len(argv) != 2 or argv[0] not in ("open", "close"):
        print(__doc__, file=sys.stderr)
        return 2
    action, path = argv
    if action == "open":
        open_issue(path)
    else:
        close_issue()
    return 0


if __name__ == "__main__":
    sys.exit(main())
